[package]
name = "srs-4l"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1"
leb128 = "0.2.5"
smallvec = { version = "1.9.0", features = ["union"] }
